### ISSUE TITLE
update docker-compose

### ISSUE THREAD

**Issue by konvergence** [admirito/gvm-containers#9]
Hi,

Here a proposal of docker-compose.yml that not use host path for /var/run and not use volumes_from

```
version: '2.1'
volumes:
  redis-data: {}
  openvas-var-lib: {}
  gvm-var-lib: {}
  postgres-data: {}
  run-redis: {}
  run-ospd: {}
  
  
services:
  gvm-postgres:
    image: admirito/gvm-postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gvmd
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: gvmduser
    stdin_open: true
    volumes:
    - postgres-data:/var/lib/postgresql/data

  gvmd:
    #  CONNECTED     9598310  /var/run/ospd/ospd.sock
    image: admirito/gvmd:11
    environment:
      GVMD_POSTGRESQL_URI: postgresql://gvmduser:mypassword@gvm-postgres:5432/gvmd?application_name=gvmd
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    depends_on:
      postgres:
        condition: gvm-postgres

  gsad:
    image: admirito/gsad:11
    ports:
    - 8080:80

    environment:
      GVMD_HOST: gvmd
      GVMD_PORT: '9390'

    depends_on:
      postgres:
        condition: gvmd

  openvas:
    # LISTENING     9431657  /var/run/ospd/ospd.sock
    # CONNECTED     9499517  /var/run/redis/redis.sock
    image: admirito/openvas:11
    environment:
      OV_PASSWORD: Securepassword41
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    depends_on:
      postgres:
        condition: gvmd



# on node must  add     vm.overcommit_memory=1 into /etc/systcl.conf
  redis:
    # LISTENING     9418817  /var/run/redis/redis.sock
    image: redis:5.0
    volumes:
    - run-redis:/var/run/redis
    - redis-data:/data
    command: redis-server --port 0 --unixsocket /var/run/redis/redis.sock --unixsocketperm 755
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    depends_on:
      postgres:
        condition: openvas


  cert-sync:
    image: admirito/gvmd:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-certdata-sync --curl --verbose

    depends_on:
      postgres:
        condition: gvmd
        
  scap-sync:
    image: admirito/gvmd:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-scapdata-sync --curl --verbose

    depends_on:
      postgres:
        condition: gvmd



  nvt-sync:
    image: admirito/openvas:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-nvt-sync

    depends_on:
      postgres:
        condition: gvmd
        


```

**Comment by konvergence** [comment]
please look my pull request

**Comment by avancerapide** [comment]
Hello @konvergence,

I try your proposal of docker-compose.yml but when I launch "docker-compose up" it return me these messages:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.gvmd.depends_on.postgres.condition contains "gvm-postgres", which is an invalid type, it should be a service_started, or a service_healthy
services.cert-sync.depends_on.postgres.condition contains "gvmd", which is an invalid type, it should be a service_started, or a service_healthy
services.gsad.depends_on.postgres.condition contains "gvmd", which is an invalid type, it should be a service_started, or a service_healthy
services.nvt-sync.depends_on.postgres.condition contains "gvmd", which is an invalid type, it should be a service_started, or a service_healthy
services.openvas.depends_on.postgres.condition contains "gvmd", which is an invalid type, it should be a service_started, or a service_healthy
services.scap-sync.depends_on.postgres.condition contains "gvmd", which is an invalid type, it should be a service_started, or a service_healthy
services.redis.depends_on.postgres.condition contains "openvas", which is an invalid type, it should be a service_started, or a service_healthy
```

**Comment by konvergence** [comment]
Yes sorry

Here the good one

```console
version: '2.1'
volumes:
  redis-data: {}
  openvas-var-lib: {}
  gvm-var-lib: {}
  postgres-data: {}
  run-redis: {}
  run-ospd: {}
  
  
services:
  gvm-postgres:
    image: admirito/gvm-postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gvmd
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: gvmduser
    stdin_open: true
    volumes:
    - postgres-data:/var/lib/postgresql/data

  gvmd:
    #  CONNECTED     9598310  /var/run/ospd/ospd.sock
    image: admirito/gvmd:11
    environment:
      GVMD_POSTGRESQL_URI: postgresql://gvmduser:mypassword@gvm-postgres:5432/gvmd?application_name=gvmd
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    depends_on:
      gvm-postgres:
        condition: service_started

  gsad:
    image: admirito/gsad:11
    ports:
    - 8080:80
    
    environment:
      GVMD_HOST: gvmd
      GVMD_PORT: '9390'

    depends_on:
      gvmd:
        condition: service_started

  openvas:
    # LISTENING     9431657  /var/run/ospd/ospd.sock
    # CONNECTED     9499517  /var/run/redis/redis.sock
    image: admirito/openvas:11
    environment:
      OV_PASSWORD: Securepassword41
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd

    depends_on:
      gvm-postgres:
        condition: service_started



# on node must  add     vm.overcommit_memory=1 into /etc/systcl.conf
  redis:
    # LISTENING     9418817  /var/run/redis/redis.sock
    image: redis:5.0
    volumes:
    - run-redis:/var/run/redis
    - redis-data:/data
    command: redis-server --port 0 --unixsocket /var/run/redis/redis.sock --unixsocketperm 755
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'

    depends_on:
      openvas:
        condition: service_started



  cert-sync:
    image: admirito/gvmd:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-certdata-sync --curl --verbose

    depends_on:
      gvmd:
        condition: service_started
        
  scap-sync:
    image: admirito/gvmd:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-scapdata-sync --curl --verbose

    depends_on:
      gvmd:
        condition: service_started


  nvt-sync:
    image: admirito/openvas:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-nvt-sync

    depends_on:
      gvmd:
        condition: service_started
        


```

**Comment by avancerapide** [comment]
I modify the docker-compose.yml like this :
-upgrade version to 3.7
-comment all "depends_on" following this thread: https://forums.docker.com/t/depends-on-version-3/29463 and https://docs.docker.com/compose/compose-file/#depends_on.

And docker-compose up running, but I've many other warnings messages like:
`gvmd_1          | md manage:WARNING:2020-03-27 09h52.51 utc:171: manage_update_nvt_cache_osp: failed to connect to /var/run/ospd/ospd.sock`

My docker-compose.yml:
```
version: '3.7'
volumes:
  redis-data: {}
  openvas-var-lib: {}
  gvm-var-lib: {}
  postgres-data: {}
  run-redis: {}
  run-ospd: {}


services:
  gvm-postgres:
    image: admirito/gvm-postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gvmd
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: gvmduser
    stdin_open: true
    volumes:
    - postgres-data:/var/lib/postgresql/data

  gvmd:
    #  CONNECTED     9598310  /var/run/ospd/ospd.sock
    image: admirito/gvmd:11
    environment:
      GVMD_POSTGRESQL_URI: postgresql://gvmduser:mypassword@gvm-postgres:5432/gvmd?application_name=gvmd
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
#    depends_on:
#      postgres:
#        condition: gvm-postgres

  gsad:
    image: admirito/gsad:11
    ports:
    - 8080:80

    environment:
      GVMD_HOST: gvmd
      GVMD_PORT: '9390'

      #    depends_on:
      #postgres:
      #  condition: gvmd

  openvas:
    # LISTENING     9431657  /var/run/ospd/ospd.sock
    # CONNECTED     9499517  /var/run/redis/redis.sock
    image: admirito/openvas:11
    environment:
      OV_PASSWORD: Securepassword41
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
      #depends_on:
      #postgres:
      #  condition: gvmd



# on node must  add     vm.overcommit_memory=1 into /etc/systcl.conf
  redis:
    # LISTENING     9418817  /var/run/redis/redis.sock
    image: redis:5.0
    volumes:
    - run-redis:/var/run/redis
    - redis-data:/data
    command: redis-server --port 0 --unixsocket /var/run/redis/redis.sock --unixsocketperm 755
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
      #depends_on:
      #postgres:
      #  condition: openvas


  cert-sync:
    image: admirito/gvmd:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-certdata-sync --curl --verbose

    #depends_on:
    #  postgres:
    #    condition: gvmd

  scap-sync:
    image: admirito/gvmd:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - gvm-var-lib:/var/lib/gvm
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-scapdata-sync --curl --verbose

    #depends_on:
    #  postgres:
    #    condition: gvmd



  nvt-sync:
    image: admirito/openvas:11
    volumes:
    - openvas-var-lib:/var/lib/openvas
    - run-redis:/var/run/redis
    - run-ospd:/var/run/ospd
    command: greenbone-nvt-sync

    #depends_on:
    #  postgres:
    #    condition: gvmd
```

**Comment by avancerapide** [comment]
Thanks, 
I try it, docker-compose up running, 
but I've many other warnings messages like:
```
redis_1         | 1:M 27 Mar 2020 10:19:04.976 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
redis_1         | 1:M 27 Mar 2020 10:19:04.976 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
```
and 

`gvmd_1 | md manage:WARNING:2020-03-27 09h52.51 utc:171: manage_update_nvt_cache_osp: failed to connect to /var/run/ospd/ospd.sock`

I will investigate ... 
:-)

**Comment by konvergence** [comment]
this messages are because you have to change the max file descriptors
https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/


or update your docker-compose with
```
ulimits:
    nofile:
       soft: 65536
       hard: 65536
```
